/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NutCarousel: typeof import('./src/components/NutCarousel.vue')['default']
    NutImagePreview: typeof import('@nutui/nutui-taro')['ImagePreview']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
  }
}
