/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NutImagePreview: typeof import('@nutui/nutui-taro')['ImagePreview']
  }
}
